sudo: required
services:
  - docker
before_install:
  - docker build -t arpitpriv/docker-multi:latest -f client/Dockerfile.dev ./client
script:
  - docker run -e CI=true arpitpriv/docker-multi:latest npm run test -- --coverage

after_success:
  - docker build -t arpitpriv/multi-client ./client
  - docker build -t arpitpriv/multi-nginx ./nginx
  - docker build -t arpitpriv/multi-server ./server
  - docker build -t arpitpriv/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push arpitpriv/multi-client
  - docker push arpitpriv/multi-nginx
  - docker push arpitpriv/multi-server
  - docker push arpitpriv/multi-worker

# s3 error is still there check
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-multi"
  env: "DockerMulti-env"
  bucket_name: "elasticbeanstalk-us-east-2-943977056781"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
