sudo: required
services:
  - docker
before_install:
  - docker build -t arpitpriv/docker-multi:latest -f client/Dockerfile.dev ./client
script:
  - docker run -e CI=true arpitpriv/docker-multi:latest npm run test -- --coverage

after_success:
  - docker build -t arpitpriv/multi-client ./client
  - docker build -t arpitpriv/multi-nginx ./nginx
  - docker build -t arpitpriv/multi-server ./server
  - docker build -t arpitpriv/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push arpitpriv/multi-client
  - docker push arpitpriv/multi-nginx
  - docker push arpitpriv/multi-server
  - docker push arpitpriv/multi-worker
